export const curatedPlayers = [
  // ═══════════════════════ ATTACKERS ═══════════════════════
  { id: 276, name: "Neymar Jr", pos: "ATK", acceptableAnswers: ["Neymar", "Neymar Jr"] },
  { id: 154, name: "Robert Lewandowski", pos: "ATK", acceptableAnswers: ["Robert Lewandowski", "Lewandowski"] },
  { id: 874, name: "Antoine Griezmann", pos: "ATK", acceptableAnswers: ["Antoine Griezmann", "Griezmann"] },
  { id: 306, name: "Mohamed Salah", pos: "ATK", acceptableAnswers: ["Mohamed Salah", "Mo Salah", "Salah"] },
  { id: 1100, name: "Erling Haaland", pos: "ATK", acceptableAnswers: ["Erling Haaland", "Haaland"] },
  { id: 278, name: "Kylian Mbappé", pos: "ATK", acceptableAnswers: ["Kylian Mbappé", "Mbappé", "Mbappe"] },
  { id: 1427, name: "Eden Hazard", pos: "ATK", acceptableAnswers: ["Eden Hazard", "Hazard"] },
  { id: 759, name: "Karim Benzema", pos: "ATK", acceptableAnswers: ["Karim Benzema", "Benzema"] },
  { id: 1460, name: "Pierre-Emerick Aubameyang", pos: "ATK", acceptableAnswers: ["Aubameyang", "Pierre-Emerick Aubameyang"] },
  { id: 739, name: "Gareth Bale", pos: "ATK", acceptableAnswers: ["Gareth Bale", "Bale"] },
  { id: 186, name: "Luis Suárez", pos: "ATK", acceptableAnswers: ["Luis Suárez", "Suárez", "Suarez"] },
  { id: 735, name: "Son Heung-min", pos: "ATK", acceptableAnswers: ["Son Heung-min", "Son", "Sonny"] },
  { id: 1585, name: "Ángel Di María", pos: "ATK", acceptableAnswers: ["Ángel Di María", "Di María", "Di Maria"] },
  { id: 2783, name: "Cristiano Ronaldo", pos: "ATK", acceptableAnswers: ["Cristiano Ronaldo", "Ronaldo", "CR7"] },
  { id: 1547, name: "Sadio Mané", pos: "ATK", acceptableAnswers: ["Sadio Mané", "Mané", "Mane"] },
  { id: 1579, name: "Romelu Lukaku", pos: "ATK", acceptableAnswers: ["Romelu Lukaku", "Lukaku"] },
  { id: 1580, name: "Edinson Cavani", pos: "ATK", acceptableAnswers: ["Edinson Cavani", "Cavani"] },
  { id: 280, name: "Ousmane Dembélé", pos: "ATK", acceptableAnswers: ["Ousmane Dembélé", "Dembélé"] },
  { id: 1496, name: "Raphinha", pos: "ATK", acceptableAnswers: ["Raphinha"] },
  { id: 1320, name: "Antony", pos: "ATK", acceptableAnswers: ["Antony"] },
  { id: 1179, name: "João Félix", pos: "ATK", acceptableAnswers: ["João Félix", "João Felix"] },
  { id: 217, name: "Memphis Depay", pos: "ATK", acceptableAnswers: ["Memphis Depay", "Depay", "Memphis"] },
  { id: 633, name: "Kingsley Coman", pos: "ATK", acceptableAnswers: ["Kingsley Coman", "Coman"] },
  { id: 1361, name: "Leroy Sané", pos: "ATK", acceptableAnswers: ["Leroy Sané", "Sané"] },
  { id: 643, name: "Gabriel Jesus", pos: "ATK", acceptableAnswers: ["Gabriel Jesus", "Jesus"] },
  { id: 909, name: "Marcus Rashford", pos: "ATK", acceptableAnswers: ["Marcus Rashford", "Rashford"] },
  { id: 762, name: "Vinícius Júnior", pos: "ATK", acceptableAnswers: ["Vinícius Jr", "Vini Jr", "Vinícius Júnior"] },
  { id: 401171, name: "Lamine Yamal", pos: "ATK", acceptableAnswers: ["Lamine Yamal", "Yamal"] },
  { id: 978, name: "Kai Havertz", pos: "ATK", acceptableAnswers: ["Kai Havertz", "Havertz"] },
  { id: 931, name: "Ferran Torres", pos: "ATK", acceptableAnswers: ["Ferran Torres"] },
  { id: 521, name: "Robert Lewandowski", pos: "ATK", acceptableAnswers: ["Lewandowski"] },
  { id: 184, name: "Harry Kane", pos: "ATK", acceptableAnswers: ["Harry Kane", "Kane"] },
  { id: 18, name: "Olivier Giroud", pos: "ATK", acceptableAnswers: ["Olivier Giroud", "Giroud"] },
  { id: 1078, name: "Álvaro Morata", pos: "ATK", acceptableAnswers: ["Álvaro Morata", "Morata"] },
  { id: 129718, name: "Jude Bellingham", pos: "ATK", acceptableAnswers: ["Jude Bellingham", "Bellingham"] },
  { id: 1100, name: "Victor Osimhen", pos: "ATK", acceptableAnswers: ["Victor Osimhen", "Osimhen"] },
  { id: 47380, name: "Darwin Núñez", pos: "ATK", acceptableAnswers: ["Darwin Núñez", "Núñez"] },
  { id: 1558, name: "Richarlison", pos: "ATK", acceptableAnswers: ["Richarlison"] },
  { id: 2413, name: "Alexander Isak", pos: "ATK", acceptableAnswers: ["Alexander Isak", "Isak"] },
  { id: 174, name: "Jamie Vardy", pos: "ATK", acceptableAnswers: ["Jamie Vardy", "Vardy"] },
  { id: 545, name: "Alexis Sánchez", pos: "ATK", acceptableAnswers: ["Alexis Sánchez", "Alexis"] },
  { id: 35845, name: "Zlatan Ibrahimović", pos: "ATK", acceptableAnswers: ["Zlatan Ibrahimović", "Ibrahimović", "Zlatan"] },
  { id: 2289, name: "Radamel Falcao", pos: "ATK", acceptableAnswers: ["Radamel Falcao", "Falcao"] },
  { id: 22221, name: "Thierry Henry", pos: "ATK", acceptableAnswers: ["Thierry Henry", "Henry"] },
  { id: 35832, name: "Didier Drogba", pos: "ATK", acceptableAnswers: ["Didier Drogba", "Drogba"] },
  { id: 35598, name: "Samuel Eto'o", pos: "ATK", acceptableAnswers: ["Samuel Eto'o", "Eto'o"] },
  { id: 35625, name: "Ronaldinho", pos: "ATK", acceptableAnswers: ["Ronaldinho"] },
  { id: 1946, name: "Leandro Trossard", pos: "ATK", acceptableAnswers: ["Leandro Trossard", "Trossard"] },
  { id: 127769, name: "Gabriel Martinelli", pos: "ATK", acceptableAnswers: ["Gabriel Martinelli", "Martinelli"] },
  { id: 18979, name: "Viktor Gyökeres", pos: "ATK", acceptableAnswers: ["Viktor Gyökeres", "Gyökeres"] },
  { id: 2341, name: "Timo Werner", pos: "ATK", acceptableAnswers: ["Timo Werner", "Werner"] },
  { id: 47339, name: "Dusan Vlahovic", pos: "ATK", acceptableAnswers: ["Dusan Vlahovic", "Vlahovic"] },
  { id: 281, name: "Mauro Icardi", pos: "ATK", acceptableAnswers: ["Mauro Icardi", "Icardi"] },
  { id: 1319, name: "Raheem Sterling", pos: "ATK", acceptableAnswers: ["Raheem Sterling", "Sterling"] },
  { id: 37, name: "Nicolas Pépé", pos: "ATK", acceptableAnswers: ["Nicolas Pépé", "Pépé"] },
  { id: 1569, name: "Ciro Immobile", pos: "ATK", acceptableAnswers: ["Ciro Immobile", "Immobile"] },
  { id: 2170, name: "André Silva", pos: "ATK", acceptableAnswers: ["André Silva"] },
  { id: 1278, name: "Marco Reus", pos: "ATK", acceptableAnswers: ["Marco Reus", "Reus"] },
  { id: 191, name: "Roberto Firmino", pos: "ATK", acceptableAnswers: ["Roberto Firmino", "Firmino"] },
  { id: 1580, name: "Alexandre Lacazette", pos: "ATK", acceptableAnswers: ["Alexandre Lacazette", "Lacazette"] },
  { id: 47, name: "Wayne Rooney", pos: "ATK", acceptableAnswers: ["Wayne Rooney", "Rooney"] },
  { id: 667, name: "Gonzalo Higuaín", pos: "ATK", acceptableAnswers: ["Gonzalo Higuaín", "Higuaín"] },
  { id: 2779, name: "Sergio Agüero", pos: "ATK", acceptableAnswers: ["Sergio Agüero", "Agüero", "Kun Agüero"] },
  { id: 159, name: "Bailly", pos: "ATK", acceptableAnswers: ["Bailly"] },

  // ═══════════════════════ MIDFIELDERS ═══════════════════════
  { id: 629, name: "Kevin De Bruyne", pos: "MF", acceptableAnswers: ["Kevin De Bruyne", "De Bruyne", "KDB"] },
  { id: 756, name: "Luka Modrić", pos: "MF", acceptableAnswers: ["Luka Modrić", "Modrić", "Modric"] },
  { id: 882, name: "Paul Pogba", pos: "MF", acceptableAnswers: ["Paul Pogba", "Pogba"] },
  { id: 47380, name: "Bruno Fernandes", pos: "MF", acceptableAnswers: ["Bruno Fernandes", "Bruno"] },
  { id: 1277, name: "Toni Kroos", pos: "MF", acceptableAnswers: ["Toni Kroos", "Kroos"] },
  { id: 746, name: "Ivan Rakitić", pos: "MF", acceptableAnswers: ["Ivan Rakitić", "Rakitić"] },
  { id: 2553, name: "Declan Rice", pos: "MF", acceptableAnswers: ["Declan Rice", "Rice"] },
  { id: 2192, name: "Rodri", pos: "MF", acceptableAnswers: ["Rodri"] },
  { id: 538, name: "Frenkie de Jong", pos: "MF", acceptableAnswers: ["Frenkie de Jong", "De Jong"] },
  { id: 37127, name: "Martin Ødegaard", pos: "MF", acceptableAnswers: ["Martin Ødegaard", "Ødegaard"] },
  { id: 632, name: "İlkay Gündoğan", pos: "MF", acceptableAnswers: ["İlkay Gündoğan", "Gündoğan"] },
  { id: 1572, name: "Christian Eriksen", pos: "MF", acceptableAnswers: ["Christian Eriksen", "Eriksen"] },
  { id: 133609, name: "Pedri", pos: "MF", acceptableAnswers: ["Pedri"] },
  { id: 1323, name: "Dani Olmo", pos: "MF", acceptableAnswers: ["Dani Olmo", "Olmo"] },
  { id: 181812, name: "Jamal Musiala", pos: "MF", acceptableAnswers: ["Jamal Musiala", "Musiala"] },
  { id: 502, name: "Joshua Kimmich", pos: "MF", acceptableAnswers: ["Joshua Kimmich", "Kimmich"] },
  { id: 511, name: "Leon Goretzka", pos: "MF", acceptableAnswers: ["Leon Goretzka", "Goretzka"] },
  { id: 47311, name: "Mikel Merino", pos: "MF", acceptableAnswers: ["Mikel Merino", "Merino"] },
  { id: 2937, name: "Declan Rice", pos: "MF" },
  { id: 1460, name: "Bukayo Saka", pos: "MF", acceptableAnswers: ["Bukayo Saka", "Saka"] },
  { id: 136723, name: "Noni Madueke", pos: "MF", acceptableAnswers: ["Noni Madueke", "Madueke"] },
  { id: 329728, name: "Marc Casadó", pos: "MF", acceptableAnswers: ["Marc Casadó", "Casadó"] },
  { id: 1, name: "Zinedine Zidane", pos: "MF", acceptableAnswers: ["Zinedine Zidane", "Zidane"] },
  { id: 159, name: "Mesut Özil", pos: "MF", acceptableAnswers: ["Mesut Özil", "Özil"] },
  { id: 522, name: "Thomas Müller", pos: "MF", acceptableAnswers: ["Thomas Müller", "Müller"] },
  { id: 157, name: "James Rodríguez", pos: "MF", acceptableAnswers: ["James Rodríguez", "James"] },
  { id: 162, name: "Isco", pos: "MF", acceptableAnswers: ["Isco"] },
  { id: 288, name: "Thiago Alcántara", pos: "MF", acceptableAnswers: ["Thiago Alcántara", "Thiago"] },
  { id: 163, name: "Casemiro", pos: "MF", acceptableAnswers: ["Casemiro"] },
  { id: 290, name: "Marco Verratti", pos: "MF", acceptableAnswers: ["Marco Verratti", "Verratti"] },
  { id: 753, name: "N'Golo Kanté", pos: "MF", acceptableAnswers: ["N'Golo Kanté", "Kanté"] },
  { id: 2285, name: "Federico Valverde", pos: "MF", acceptableAnswers: ["Federico Valverde", "Valverde"] },
  { id: 523, name: "Serge Gnabry", pos: "MF", acceptableAnswers: ["Serge Gnabry", "Gnabry"] },
  { id: 878, name: "Phil Foden", pos: "MF", acceptableAnswers: ["Phil Foden", "Foden"] },
  { id: 1161, name: "Florian Wirtz", pos: "MF", acceptableAnswers: ["Florian Wirtz", "Wirtz"] },
  { id: 10, name: "Arturo Vidal", pos: "MF", acceptableAnswers: ["Arturo Vidal", "Vidal"] },
  { id: 880, name: "Mason Mount", pos: "MF", acceptableAnswers: ["Mason Mount", "Mount"] },
  { id: 985, name: "Bernardo Silva", pos: "MF", acceptableAnswers: ["Bernardo Silva"] },
  { id: 19586, name: "Eberechi Eze", pos: "MF", acceptableAnswers: ["Eberechi Eze", "Eze"] },
  { id: 889, name: "Jack Grealish", pos: "MF", acceptableAnswers: ["Jack Grealish", "Grealish"] },
  { id: 182, name: "Riyad Mahrez", pos: "MF", acceptableAnswers: ["Riyad Mahrez", "Mahrez"] },
  { id: 158, name: "Hakim Ziyech", pos: "MF", acceptableAnswers: ["Hakim Ziyech", "Ziyech"] },
  { id: 903, name: "Lucas Moura", pos: "MF", acceptableAnswers: ["Lucas Moura"] },
  { id: 286, name: "Xavi Hernández", pos: "MF", acceptableAnswers: ["Xavi Hernández", "Xavi"] },
  { id: 30, name: "Andrea Pirlo", pos: "MF", acceptableAnswers: ["Andrea Pirlo", "Pirlo"] },
  { id: 155, name: "Steven Gerrard", pos: "MF", acceptableAnswers: ["Steven Gerrard", "Gerrard"] },
  { id: 160, name: "Frank Lampard", pos: "MF", acceptableAnswers: ["Frank Lampard", "Lampard"] },
  { id: 289, name: "David Beckham", pos: "MF", acceptableAnswers: ["David Beckham", "Beckham"] },
  { id: 622, name: "Cesc Fàbregas", pos: "MF", acceptableAnswers: ["Cesc Fàbregas", "Fàbregas"] },
  { id: 747, name: "Mateo Kovačić", pos: "MF", acceptableAnswers: ["Mateo Kovačić", "Kovačić"] },
  { id: 741, name: "Dele Alli", pos: "MF", acceptableAnswers: ["Dele Alli", "Dele"] },

  // ═══════════════════════ DEFENDERS ═══════════════════════
  { id: 886, name: "Sergio Ramos", pos: "DF", acceptableAnswers: ["Sergio Ramos", "Ramos"] },
  { id: 1514, name: "Antonio Rüdiger", pos: "DF", acceptableAnswers: ["Antonio Rüdiger", "Rüdiger"] },
  { id: 2295, name: "Achraf Hakimi", pos: "DF", acceptableAnswers: ["Achraf Hakimi", "Hakimi"] },
  { id: 855, name: "João Cancelo", pos: "DF", acceptableAnswers: ["João Cancelo", "Cancelo"] },
  { id: 1582, name: "Kalidou Koulibaly", pos: "DF", acceptableAnswers: ["Kalidou Koulibaly", "Koulibaly"] },
  { id: 22224, name: "Gabriel Magalhães", pos: "DF", acceptableAnswers: ["Gabriel Magalhães", "Gabriel"] },
  { id: 157052, name: "Riccardo Calafiori", pos: "DF", acceptableAnswers: ["Riccardo Calafiori", "Calafiori"] },
  { id: 127817, name: "Piero Hincapié", pos: "DF", acceptableAnswers: ["Piero Hincapié", "Hincapié"] },
  { id: 22090, name: "William Saliba", pos: "DF", acceptableAnswers: ["William Saliba", "Saliba"] },
  { id: 38746, name: "Jurriën Timber", pos: "DF", acceptableAnswers: ["Jurriën Timber", "Timber"] },
  { id: 19959, name: "Ben White", pos: "DF", acceptableAnswers: ["Ben White", "White"] },
  { id: 509, name: "Alphonso Davies", pos: "DF", acceptableAnswers: ["Alphonso Davies", "Davies"] },
  { id: 972, name: "Jonathan Tah", pos: "DF", acceptableAnswers: ["Jonathan Tah", "Tah"] },
  { id: 1149, name: "Dayot Upamecano", pos: "DF", acceptableAnswers: ["Dayot Upamecano", "Upamecano"] },
  { id: 2897, name: "Kim Min-Jae", pos: "DF", acceptableAnswers: ["Kim Min-Jae", "Kim"] },
  { id: 8, name: "Raphaël Guerreiro", pos: "DF", acceptableAnswers: ["Raphaël Guerreiro", "Guerreiro"] },
  { id: 570, name: "Virgil van Dijk", pos: "DF", acceptableAnswers: ["Virgil van Dijk", "Van Dijk"] },
  { id: 883, name: "Raphaël Varane", pos: "DF", acceptableAnswers: ["Raphaël Varane", "Varane"] },
  { id: 754, name: "Marcelo", pos: "DF", acceptableAnswers: ["Marcelo"] },
  { id: 101814, name: "Ronald Araújo", pos: "DF", acceptableAnswers: ["Ronald Araújo", "Araújo"] },
  { id: 1257, name: "Jules Koundé", pos: "DF", acceptableAnswers: ["Jules Koundé", "Koundé"] },
  { id: 619, name: "Eric García", pos: "DF", acceptableAnswers: ["Eric García"] },
  { id: 2282, name: "Andreas Christensen", pos: "DF", acceptableAnswers: ["Andreas Christensen", "Christensen"] },
  { id: 2, name: "Thiago Silva", pos: "DF", acceptableAnswers: ["Thiago Silva"] },
  { id: 879, name: "Trent Alexander-Arnold", pos: "DF", acceptableAnswers: ["Trent Alexander-Arnold", "TAA"] },
  { id: 869, name: "Andy Robertson", pos: "DF", acceptableAnswers: ["Andy Robertson", "Robertson"] },
  { id: 744, name: "Kyle Walker", pos: "DF", acceptableAnswers: ["Kyle Walker", "Walker"] },
  { id: 891, name: "Luke Shaw", pos: "DF", acceptableAnswers: ["Luke Shaw", "Shaw"] },
  { id: 19, name: "Dani Alves", pos: "DF", acceptableAnswers: ["Dani Alves", "Alves"] },
  { id: 663, name: "Gerard Piqué", pos: "DF", acceptableAnswers: ["Gerard Piqué", "Piqué"] },
  { id: 25, name: "Jordi Alba", pos: "DF", acceptableAnswers: ["Jordi Alba"] },
  { id: 1590, name: "Mats Hummels", pos: "DF", acceptableAnswers: ["Mats Hummels", "Hummels"] },
  { id: 15, name: "David Luiz", pos: "DF", acceptableAnswers: ["David Luiz"] },
  { id: 887, name: "Harry Maguire", pos: "DF", acceptableAnswers: ["Harry Maguire", "Maguire"] },
  { id: 20, name: "Pepe", pos: "DF", acceptableAnswers: ["Pepe"] },
  { id: 7, name: "Philipp Lahm", pos: "DF", acceptableAnswers: ["Philipp Lahm", "Lahm"] },
  { id: 884, name: "Lisandro Martínez", pos: "DF", acceptableAnswers: ["Lisandro Martínez", "Martínez"] },
  { id: 135, name: "Matthijs de Ligt", pos: "DF", acceptableAnswers: ["Matthijs de Ligt", "De Ligt"] },
  { id: 139, name: "Aymeric Laporte", pos: "DF", acceptableAnswers: ["Aymeric Laporte", "Laporte"] },
  { id: 1589, name: "Presnel Kimpembe", pos: "DF", acceptableAnswers: ["Presnel Kimpembe", "Kimpembe"] },
  { id: 1157, name: "Konrad Laimer", pos: "DF", acceptableAnswers: ["Konrad Laimer", "Laimer"] },

  // ═══════════════════════ GOALKEEPERS ═══════════════════════
  { id: 730, name: "Thibaut Courtois", pos: "GK", acceptableAnswers: ["Thibaut Courtois", "Courtois"] },
  { id: 644, name: "Jan Oblak", pos: "GK", acceptableAnswers: ["Jan Oblak", "Oblak"] },
  { id: 1599, name: "Gianluigi Donnarumma", pos: "GK", acceptableAnswers: ["Gianluigi Donnarumma", "Donnarumma"] },
  { id: 3790, name: "David de Gea", pos: "GK", acceptableAnswers: ["David de Gea", "De Gea"] },
  { id: 399, name: "Alisson Becker", pos: "GK", acceptableAnswers: ["Alisson Becker", "Alisson"] },
  { id: 617, name: "Ederson", pos: "GK", acceptableAnswers: ["Ederson"] },
  { id: 35642, name: "Gianluigi Buffon", pos: "GK", acceptableAnswers: ["Gianluigi Buffon", "Buffon"] },
  { id: 757, name: "Hugo Lloris", pos: "GK", acceptableAnswers: ["Hugo Lloris", "Lloris"] },
  { id: 497, name: "Manuel Neuer", pos: "GK", acceptableAnswers: ["Manuel Neuer", "Neuer"] },
  { id: 851, name: "Wojciech Szczęsny", pos: "GK", acceptableAnswers: ["Wojciech Szczęsny", "Szczęsny"] },
  { id: 2273, name: "Kepa Arrizabalaga", pos: "GK", acceptableAnswers: ["Kepa Arrizabalaga", "Kepa"] },
  { id: 19465, name: "David Raya", pos: "GK", acceptableAnswers: ["David Raya", "Raya"] },
  { id: 168, name: "Marc-André ter Stegen", pos: "GK", acceptableAnswers: ["Marc-André ter Stegen", "Ter Stegen"] },
  { id: 758, name: "Keylor Navas", pos: "GK", acceptableAnswers: ["Keylor Navas", "Navas"] },
  { id: 35476, name: "Iker Casillas", pos: "GK", acceptableAnswers: ["Iker Casillas", "Casillas"] },
  { id: 162, name: "Peter Čech", pos: "GK", acceptableAnswers: ["Peter Čech", "Čech", "Cech"] },
  { id: 274, name: "André Onana", pos: "GK", acceptableAnswers: ["André Onana", "Onana"] },

  // ═══════════════════════ ADDITIONAL ATTACKERS (More variety) ═══════════════════════
  { id: 291, name: "Thomas Lemar", pos: "ATK", acceptableAnswers: ["Thomas Lemar", "Lemar"] },
  { id: 2291, name: "Samu Chukwueze", pos: "ATK", acceptableAnswers: ["Samu Chukwueze", "Chukwueze"] },
  { id: 530, name: "Serge Gnabry", pos: "ATK" },
  { id: 47339, name: "Dušan Vlahović", pos: "ATK" },
  { id: 6063, name: "Raphinha", pos: "ATK" },
  { id: 47359, name: "Rodrygo", pos: "ATK", acceptableAnswers: ["Rodrygo"] },
  { id: 286, name: "Endrick", pos: "ATK", acceptableAnswers: ["Endrick"] },
  { id: 47447, name: "Ansu Fati", pos: "ATK", acceptableAnswers: ["Ansu Fati", "Fati"] },
  { id: 47455, name: "Gavi", pos: "MF", acceptableAnswers: ["Gavi"] },
  { id: 1593, name: "Dries Mertens", pos: "ATK", acceptableAnswers: ["Dries Mertens", "Mertens"] },
  { id: 2776, name: "Luis Figo", pos: "MF", acceptableAnswers: ["Luís Figo", "Figo"] },
  { id: 2777, name: "Rivaldo", pos: "ATK", acceptableAnswers: ["Rivaldo"] },
  { id: 264, name: "Olivier Giroud", pos: "ATK" },
  { id: 525, name: "Robert Lewandowski", pos: "ATK" },
  { id: 1583, name: "Lorenzo Insigne", pos: "ATK", acceptableAnswers: ["Lorenzo Insigne", "Insigne"] },
  { id: 1586, name: "Saúl Ñíguez", pos: "MF", acceptableAnswers: ["Saúl Ñíguez", "Saúl"] },
  { id: 1591, name: "Axel Witsel", pos: "MF", acceptableAnswers: ["Axel Witsel", "Witsel"] },
  { id: 2284, name: "Eder Militão", pos: "DF", acceptableAnswers: ["Eder Militão", "Militão"] },
  { id: 153, name: "Willian", pos: "MF" },
  { id: 161, name: "Roberto Carlos", pos: "DF", acceptableAnswers: ["Roberto Carlos"] },
  { id: 35630, name: "Patrick Vieira", pos: "MF", acceptableAnswers: ["Patrick Vieira", "Vieira"] },
  { id: 35627, name: "Edgar Davids", pos: "MF", acceptableAnswers: ["Edgar Davids", "Davids"] },
  { id: 35628, name: "Michael Ballack", pos: "MF", acceptableAnswers: ["Michael Ballack", "Ballack"] },
  { id: 743, name: "Danny Rose", pos: "DF", acceptableAnswers: ["Danny Rose"] },
  { id: 156, name: "Rio Ferdinand", pos: "DF", acceptableAnswers: ["Rio Ferdinand", "Ferdinand"] },
  { id: 896, name: "Diogo Jota", pos: "ATK", acceptableAnswers: ["Diogo Jota", "Jota"] },
  { id: 886, name: "Sergio Ramos", pos: "DF" },
  { id: 2286, name: "Vinícius Tobias", pos: "DF" },
  { id: 742, name: "Jan Vertonghen", pos: "DF", acceptableAnswers: ["Jan Vertonghen", "Vertonghen"] },
  { id: 282, name: "Samuel Umtiti", pos: "DF", acceptableAnswers: ["Samuel Umtiti", "Umtiti"] },
  { id: 665, name: "Sergio Agüero", pos: "ATK" }
];
